version: "3.0"

services:
  hlds:
    image: docker-hlds-won2-1104-hlds
    restart: always
    ports:
      - 27015:27015
      - 27015:27015/udp
    command:
      - -port 27015 -game cstrike +map cs_italy +maxplayers 16 +sv_lan 1 -sys_ticrate 10000 -pingboost 2
    security_opt:
      - no-new-privileges:true
